apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1a9/iktZtrBV6XGewwlD6Eg42w==,iv:5SgVcoeYVRIdBzIC5hrw62qpIj8AgC8jnrgnat7v3WI=,tag:eQiNMVBgkZuuUhd1vDAihg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+3SIOr1+umtEBrHbfDFDHmkjMSxbY/Xy7w==,iv:jCGcqXg1j1yQk1tKALcVKAj/yA19ixBulILCckjuAQ4=,tag:KXoxUOE7mmHiOYabYwmymg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:FTtViKF0jTCGZR55TNpDr+tggBK27qSAqY19DTAPp182UP8/,iv:ek/V2+Ww+NZ1dsw6F8phRAxyCKVUt+AzGm6h4kTMprg=,tag:+n72xRBHr/HIw5gy88zAMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nuq9j2zj2p9u23u9dp470uneasgtvcmvsykt5sjz4l9zyhrdaves4aqw7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENWllU1VvNkdQWVVYTklq
            cjU5Z2lmbHY2Vy9tKzc2Z0pOZXJ1Wlk5RlF3Cld0aUFZOEFJdGZyNXZWZUZwUkto
            RGovc01kNVJDdE9HZWZMUmZNUVdiZncKLS0tIGRmSjJKSHZKOEZTS2dWemsraC92
            Nm9yQmZPcXVpWWhnMEx4RkQzL0dydHMKl0f0SCti9MQLwgqw7gWckEPnQGWP4t1/
            GZXmFMfLSQIK8rHCMx5ZD4mUr4ztr+TfsX6NKqdJ9fWvZ04KQaz2Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T19:52:21Z"
    mac: ENC[AES256_GCM,data:yaZNBau/WrcRs3H2xU+zWWuTuZEbNU9d4XO2p764SUQPd6ixl3Ku6n4KiubhUMIfgvXHDuWsQJ6NT/bddL8tC3JeBjXp+NvszIoJ7X0JXUgwb7qO5d8wwHxgidrKS6wcKAzBMunBTXdGaTcYbqBD5/c+A6v5ufQPWIV5Tjkepz8=,iv:eMH8T13f4HdpfZNbV8sriQScNQJUvmlywofI/Brr8BI=,tag:LR2U4gTrxaXuF2/Yidu5hA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
