apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:r9ygTORj4MFkpdC1UPvjVxl5IeZPk1H/YH3pzH+gb04=,iv:mouXAxOVr5rO8DKdC939ZrOMgul0lIUfaHKmT97OrjI=,tag:xWeemwcv3LQgoHNWYnae6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nuq9j2zj2p9u23u9dp470uneasgtvcmvsykt5sjz4l9zyhrdaves4aqw7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdldaUGtQZGJSTURpN2hD
            YkluL1lmL2toSDE1bWd5SE5kaFJwZ3Z4ZjFrCk54dlZHaWM5Q0V4UU5qN2pmRWtE
            WS95RUI5MWtYYlREVzlOSm1vSThSL0EKLS0tIDB6dGxnNTA3b1oxTHNOdGtFbUdQ
            RkJ5QVJ0U3FLL21KNW04czhLcWFEZ0kK7HtGMpij4g7OBbZnx/+XWpXdB+2oJVtC
            2Ws1/TV7Yt0B2qXy1bxvtLjeLztsW8oqtgcAXxns8sAP9Ry44E7n1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T19:39:43Z"
    mac: ENC[AES256_GCM,data:zo7SGaGAmEHex8JPe7BEfRCQUHh9FJurDMvAzOGeRTxf+r3WGZDha2bakaP1frxS5fr5tEJT3UGVdLoxl15vwmtNHKLpvlTilqVHSboc+rNY+Cwz7jPN6m5ADGGeeZyp3VY+2++j7hJyqcj4tfXQLQhfW9dYwchmuqx6otV+JAA=,iv:9YRtUy//+3TSSy83EgCa1ZLx7xquhoycd7PO+VXcPUY=,tag:BQ2CEIaYIk4PwtSsum/6Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
