apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:xIblSKoXpYqVERHH/o6BuJXDz7nuAt8mSjdhBo6vxUm5j/1NIzFwLg==,iv:TyHyLFUn95/oyEzdvV2z9rfYZNRmzdxJuKTvF3Ege0E=,tag:+Kc4sJbVs05t4HIlElFyPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nuq9j2zj2p9u23u9dp470uneasgtvcmvsykt5sjz4l9zyhrdaves4aqw7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ektrK09ET0taTGdlYUxi
            UHNKM3pRQ25la3ovVGhGNmVXTEx1N2RHMmgwCjg5anFKalNwcDJnMDE3T3pzTmNR
            Ukg2VEFWejVoYkRkcDVMVXVXa2crcEUKLS0tIFphTHZzVzlaUndZNDB2OHJFTlM0
            MnNPeW1xT1Rvdyt0bGRabDV4T2Y4NU0KeNfJfD+zKsRJ5UlpOy1V0eiVoV0lls1x
            pClFF0KSgrRv527inmDPvN1+vUQOYT1fuvShX83RUzwlUbJe0BzR4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T19:52:21Z"
    mac: ENC[AES256_GCM,data:t/I+FfRWlRNPsWfMqczpC7I8KUBbve0tEfkb+rMo0g1ShPAEc4lchQY9aQDiZtHgZ18PU7Y5c2U452C5+wb0aL4tU1MOr8+HQkW3AewnrbP0vKpLUGDqqw/VhdQ+lJvXQpdGoki62hjdS5jwKv5nwPuDdMdpIxmjbJUtMJ9N9zg=,iv:Tv1Z5Ia9tIphFQT1Oop2VitlmZfP0JqA6CFfo1+RSps=,tag:Q5TOWc+yedcOwe1+qmca/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
